- import_tasks: tasks/generic/serviceaccount.yml
  vars:
    osbs_generic_serviceaccount_name: "{{ osbs_pruner_serviceaccount }}"

- name: Copy cluster rolebinding for {{ osbs_pruner_serviceaccount }} service account
  template:
    src: "openshift-rolebinding.v2.yml.j2"
    dest: "{{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-rolebinding-{{ item.name }}.yml"
  with_items:
  # For listing buildconfigs and builds
  # Must allow listing buildconfigs across all namespaces due to
  # this being required by 'oc adm prune'
  - name: "{{ osbs_namespace }}-build-pruner-read"
    role: "{{ osbs_pruner_build_clusterrole_read }}"
    type: ClusterRoleBinding
    serviceaccounts:
    - "{{ osbs_pruner_serviceaccount }}"
  # For deleting builds (in this namespace only)
  - name: "{{ osbs_namespace }}-build-pruner-delete"
    role: "{{ osbs_pruner_build_role_delete }}"
    serviceaccounts:
    - "{{ osbs_pruner_serviceaccount }}"
  register: yaml_rolebindings
  when: osbs_is_admin
  tags:
  - oc

- name: Import rolebinding for {{ osbs_pruner_serviceaccount }} service account
  command: >
    oc replace
    --namespace={{ osbs_namespace }}
    --force=true
    --filename={{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-rolebinding-{{ item.item.name }}.yml
  environment: "{{ osbs_environment }}"
  with_items: "{{ yaml_rolebindings.results }}"
  when: yaml_rolebindings.changed and item.changed
  tags:
  - oc

- import_tasks: tasks/generic/cronjob.yml
  vars:
    osbs_generic_cronjob_name: build-pruner
    osbs_generic_cronjob_serviceaccount: "{{ osbs_pruner_serviceaccount }}"
    osbs_generic_cronjob_schedule: "{{ osbs_pruner_schedule_build }}"
    osbs_generic_cronjob_successful_jobs: "{{ osbs_pruner_successful_jobs }}"
    osbs_generic_cronjob_failed_jobs: "{{ osbs_pruner_failed_jobs }}"
    osbs_generic_cronjob_image: "{{ osbs_pruner_image }}"
    osbs_generic_cronjob_command: "{{ osbs_pruner_command_build }}"
